language:
  - objective-c

cache:
  - bundler

before_install:
  - bundle install
  - cd Tests && pod install && cd $TRAVIS_BUILD_DIR

script:
  - xctool test

notifications:
  slack: slktvc:g7fiaXRUFmuMS6t3l1p7bUir

after_success:
  - bundle exec slather